/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as PreorderRouteImport } from './routes/preorder'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ApiSendReceiptRouteImport } from './routes/api/send-receipt'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const PreorderRoute = PreorderRouteImport.update({
  id: '/preorder',
  path: '/preorder',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendReceiptRoute = ApiSendReceiptRouteImport.update({
  id: '/api/send-receipt',
  path: '/api/send-receipt',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/menu': typeof MenuRoute
  '/preorder': typeof PreorderRoute
  '/about': typeof AboutRoute
  '/api/send-receipt': typeof ApiSendReceiptRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/menu': typeof MenuRoute
  '/preorder': typeof PreorderRoute
  '/about': typeof AboutRoute
  '/api/send-receipt': typeof ApiSendReceiptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/menu': typeof MenuRoute
  '/preorder': typeof PreorderRoute
  '/about': typeof AboutRoute
  '/api/send-receipt': typeof ApiSendReceiptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/menu' | '/preorder' | '/about' | '/api/send-receipt'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/menu' | '/preorder' | '/about' | '/api/send-receipt'
  id: '__root__' | '/' | '/menu' | '/preorder' | '/about' | '/api/send-receipt'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MenuRoute: typeof MenuRoute
  PreorderRoute: typeof PreorderRoute
  AboutRoute: typeof AboutRoute
  ApiSendReceiptRoute: typeof ApiSendReceiptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preorder': {
      id: '/preorder'
      path: '/preorder'
      fullPath: '/preorder'
      preLoaderRoute: typeof PreorderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-receipt': {
      id: '/api/send-receipt'
      path: '/api/send-receipt'
      fullPath: '/api/send-receipt'
      preLoaderRoute: typeof ApiSendReceiptRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MenuRoute: MenuRoute,
  PreorderRoute: PreorderRoute,
  AboutRoute: AboutRoute,
  ApiSendReceiptRoute: ApiSendReceiptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
